# HEAL Monday Studies Board Update pipeline

Jupyter Notebook to follow the SOP for update the HEAL Monday Board. 
The notebook can be used for either step by step exploration, or running from a service like Google Colab.

In [1]:
# ## If running on Google Colab, run this cell to mount Google Drive to access files on Google Drive.
# from google.colab import drive
# drive.mount('/content/drive', force_remount=True)

In [2]:
## If running from Google Colab, might need to install this library
# !pip install xlsxwriter

In [3]:
import sys
import logging
from pathlib import Path
sys.path.append('../scripts/')
import monday_board_update

In [4]:
## Set this to the directory where:
## 1- Monday Studies board has been exported.
## 2- All relevant tables from MySql database for HEAL have been exported as a csv to.
# input_dir = Path("/pat/to/data/dir")
input_dir = Path("/Users/hinashah/Documents/HEAL/MondayUpdate_May2026")

In [5]:
## Setup logger
logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s [%(levelname)s] %(message)s",
        filename= input_dir / "report-log.txt",
    )
logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))

In [6]:
logging.info("---- STEP 1: Looking at Study Lookup Table")
gt_file = monday_board_update.import_study_lookup_table(input_dir)

---- STEP 1: Looking at Study Lookup Table
Number of entries in study lookup table: 2682
Number of distinct values in --appl_id--: 2627
---- NA count: 0
Number of distinct values in --xstudy_id--: 1631
---- NA count: 0
Number of distinct values in --study_hdp_id--: 1514
---- NA count: 178
Number of distinct values in --study_hdp_id_appl--: 1490
---- NA count: 178
Number of distinct values in --study_most_recent_appl--: 1596
---- NA count: 0
Number of distinct values in --study_first_appl--: 1607
---- NA count: 0
Number of distinct values in --compound_key--: 2651
---- NA count: 0

In [7]:
logging.info("---- STEP 2: Importing Monday Studies Board")
monday_board = monday_board_update.import_monday_board(input_dir)

---- STEP 2: Importing Monday Studies Board
[PosixPath('/Users/hinashah/Documents/HEAL/MondayUpdate_May2026/HEAL_Studies_1778152375.xlsx')]
Index(['Name', '_tmp', 'Most Recent Appl_ID', 'HDP appl_ID', 'Project #',
       'Archived', 'HEAL-Related', 'Data Type', 'Research Focus',
       'Research Program', 'Research Network', 'Title', 'Contact PI',
       'Contact Email', 'Administering IC', 'NIH PO', 'NIH PO Email',
       'Institution(s)', 'PI(s)', 'Location', 'Activity Code', 'Award Type',
       'Award Year', 'Total Funded', 'Summary', 'Project Start',
       'Project End date', 'Reporter Link', 'SBIR/STTR', 'Data Engagement',
       'Repo per Platform', 'Platform Reg Time', 'CEDAR Form %',
       'Creation Log', 'study_type', '"Get the Data" Engagement Board',
       'VLMD Status', 'DD Tracker', 'Checklist Exempt', 'Do not Engage',
       'link to Data Dictionary Tracker',
       'link to Subitems of Data Dictionary Tracker'],
      dtype='object')
Number of records on Monday Board: 1681

In [8]:
logging.info("---- STEP 3: Compare lookup table and Monday Board")
mondayboard_missingin_lookup, lookup_fields = monday_board_update.compare_study_loookup_monday(gt_file, monday_board)

---- STEP 3: Compare lookup table and Monday Board
Number records from Monday already in lookup table: 1631
Number records from Monday that are not in lookup table (Consider these as discrepancies **Investigate**): 50
Number records from lookup table that are not on Monday (Potentially new entries): 0
Entries in Monday that are not in lookup table
                   Name  _tmp Most Recent Appl_ID HDP appl_ID  \
1518           HDP01285  1631                   -           -
1519           HDP01286  1632                   -           -
1520           HDP01287  1633                   -           -
1521           HDP01288  1634                   -           -
1522           HDP01289  1635                   -           -
1523           HDP01290  1636                   -           -
1524           HDP01291  1637                   -           -
1525           HDP01292  1638                   -           -
1526           HDP01293  1639                   -           -
1527           HDP01294  1640                   -           -
1528           HDP01295  1641                   -           -
1529           HDP01296  1642                   -           -
1530           HDP01297  1643                   -           -
1531           HDP01298  1644                   -           -
1532           HDP01299  1645                   -           -
1533           HDP01300  1646                   -           -
1534           HDP01301  1647                   -           -
1535           HDP01302  1648                   -           -
1536           HDP01303  1649                   -           -
1537           HDP01304  1650                   -           -
1538           HDP01305  1651                   -           -
1539           HDP01306  1652                   -           -
1540           HDP01307  1653                   -           -
1541           HDP01308  1654                   -           -
1542           HDP01309  1655                   -           -
1543           HDP01310  1656                   -           -
1544           HDP01311  1657                   -           -
1545           HDP01312  1658                   -           -
1546           HDP01314  1660                   -           -
1547           HDP01315  1661                   -           -
1548           HDP01316  1662                   -           -
1549           HDP01317  1663                   -           -
1550           HDP01313  1659                   -           -
1551           HDP01318  1664                   -           -
1552           HDP01319  1665                   -           -
1553           HDP01320  1666                   -           -
1554           HDP01321  1667                   -           -
1555           HDP01322  1668                   -           -
1556           HDP01323  1669                   -           -
1557           HDP01324  1670                   -           -
1558           HDP01504  1671                   -           -
1559           HDP01505  1672                   -           -
1560           HDP01506  1673                   -           -
1561           HDP01507  1674                   -           -
1562           HDP01686  1675                   -           -
1563           HDP01687  1676                   -           -
1568  10428343_HDP00882   NaN                 NaN         NaN
1569  10488140_HDP00883   NaN                 NaN         NaN
1570       9673173_none   NaN                 NaN         NaN
1571       9769689_none   NaN                 NaN         NaN

                                 Project #  Archived HEAL-Related Data Type  \
1518                              CTN-0130         n            N         -
1519                              CTN-0133         n            N         -
1520                            CTN-0095A2         n            N         -
1521                              CTN-0093         n            N         -
1522                              CTN-0147         n            N         -
1523                              CTN-0099         n            N         -
1524                              CTN-0088         n            N         -
1525                              CTN-0144         n            N         -
1526                          CTN-0099-A-1         n            N         -
1527                              CTN-0095         n            N         -
1528                              CTN-0098         n            N         -
1529                              CTN-0145         n            N         -
1530                              CTN-0086         n            N         -
1531                              CTN-0115         n            N         -
1532                          CTN-0084-A-1         n            N         -
1533                              CTN-0091  archived            N         -
1534                              CTN-0101         n            N         -
1535                              CTN-0139         n            N         -
1536                              CTN-0105         n            N         -
1537                              CTN-0085         n            N         -
1538                          CTN-0079-A-1         n            N         -
1539                              CTN-0089  archived            N         -
1540                              CTN-0107         n            N         -
1541                              CTN-0100         n            N         -
1542                              CTN-0103  archived            N         -
1543                              CTN-0087         n            N         -
1544                              CTN-0128         n            N         -
1545                          CTN-0095-A-1         n            N         -
1546                              CTN-0106         n            N         -
1547                              CTN-0102         n            N         -
1548                              CTN-0090         n            N         -
1549                              CTN-0080         n            N         -
1550                              CTN-0084         n            N         -
1551                          CTN-0074-A-1         n            N         -
1552                              CTN-0097         n            N         -
1553                              CTN-0110         n            N         -
1554                              CTN-0096         n            N         -
1555                          CTN-0084-A-2         n            N         -
1556                              CTN-0094         n            N         -
1557                              CTN-0146         n            N         -
1558                              CTN-0153         n            N         -
1559                              CTN-0155         n            N         -
1560                              CTN-0152         n            N         -
1561                              CTN-0154         n            N         -
1562                              CTN-0158         n            N         -
1563                              CTN-0098         n            N         -
1568             75N95020P00589-P00001-0-1       NaN          NaN       NaN
1569  75N95019D00026-P00003-759501900088-1       NaN          NaN       NaN
1570                       5U24HD095254-02       NaN          NaN       NaN
1571                       5R01DE027454-02       NaN          NaN       NaN

                                         Research Focus Research Program  ...  \
1518                                                  -                -  ...
1519                                                  -                -  ...
1520                                                  -                -  ...
1521                                                  -                -  ...
1522                                                  -                -  ...
1523                                                  -                -  ...
1524                                                  -                -  ...
1525                                                  -                -  ...
1526                                                  -                -  ...
1527                                                  -                -  ...
1528                                                  -                -  ...
1529                                                  -                -  ...
1530                                                  -                -  ...
1531                                                  -                -  ...
1532                                                  -                -  ...
1533                                                  -                -  ...
1534                                                  -                -  ...
1535                                                  -                -  ...
1536                                                  -                -  ...
1537                                                  -                -  ...
1538                                                  -                -  ...
1539                                                  -                -  ...
1540                                                  -                -  ...
1541                                                  -                -  ...
1542                                                  -                -  ...
1543                                                  -                -  ...
1544                                                  -                -  ...
1545                                                  -                -  ...
1546                                                  -                -  ...
1547                                                  -                -  ...
1548                                                  -                -  ...
1549                                                  -                -  ...
1550                                                  -                -  ...
1551                                                  -                -  ...
1552                                                  -                -  ...
1553                                                  -                -  ...
1554                                                  -                -  ...
1555                                                  -                -  ...
1556                                                  -                -  ...
1557                                                  -                -  ...
1558                                                  -                -  ...
1559                                                  -                -  ...
1560                                                  -                -  ...
1561                                                  -                -  ...
1562                                                  -                -  ...
1563                                                  -                -  ...
1568                                                NaN              NaN  ...
1569                                                NaN              NaN  ...
1570  Enhanced Outcomes for Infants and Children Exp...              NaN  ...
1571  Preclinical and Translational Research in Pain...              NaN  ...

     CEDAR Form %                      Creation Log study_type  \
1518         73.1    Hina Shah Jun 26, 2024 3:05 PM        CTN
1519         65.4    Hina Shah Jun 26, 2024 3:05 PM        CTN
1520         51.9    Hina Shah Jun 26, 2024 3:05 PM        CTN
1521         65.4    Hina Shah Jun 26, 2024 3:05 PM        CTN
1522            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1523         76.9    Hina Shah Jun 26, 2024 3:05 PM        CTN
1524         21.2    Hina Shah Jun 26, 2024 3:05 PM        CTN
1525            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1526            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1527         78.8    Hina Shah Jun 26, 2024 3:05 PM        CTN
1528         59.6    Hina Shah Jun 26, 2024 3:05 PM        CTN
1529         78.8    Hina Shah Jun 26, 2024 3:05 PM        CTN
1530            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1531         78.8    Hina Shah Jun 26, 2024 3:05 PM        CTN
1532         63.5    Hina Shah Jun 26, 2024 3:05 PM        CTN
1533            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1534         84.6    Hina Shah Jun 26, 2024 3:05 PM        CTN
1535            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1536         69.2    Hina Shah Jun 26, 2024 3:05 PM        CTN
1537            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1538           75    Hina Shah Jun 26, 2024 3:05 PM        CTN
1539            0    Hina Shah Jun 26, 2024 3:05 PM        CTN
1540           50    Hina Shah Jun 26, 2024 3:01 PM        CTN
1541            0    Hina Shah Jun 26, 2024 3:01 PM        CTN
1542            0    Hina Shah Jun 26, 2024 3:01 PM        CTN
1543         73.1    Hina Shah Jun 26, 2024 3:01 PM        CTN
1544            0    Hina Shah Jun 26, 2024 3:01 PM        CTN
1545         51.9    Hina Shah Jun 26, 2024 3:01 PM        CTN
1546            0    Hina Shah Jun 26, 2024 3:01 PM        CTN
1547            0    Hina Shah Jun 26, 2024 3:01 PM        CTN
1548         82.7    Hina Shah Jun 26, 2024 3:01 PM        CTN
1549         76.9    Hina Shah Jun 26, 2024 3:01 PM        CTN
1550         57.7    Hina Shah Jun 26, 2024 3:01 PM        CTN
1551         21.2    Hina Shah Jun 26, 2024 3:01 PM        CTN
1552         82.7    Hina Shah Jun 26, 2024 3:01 PM        CTN
1553         84.6    Hina Shah Jun 26, 2024 3:01 PM        CTN
1554         76.9    Hina Shah Jun 26, 2024 3:01 PM        CTN
1555         63.5    Hina Shah Jun 26, 2024 3:01 PM        CTN
1556          7.7    Hina Shah Jun 26, 2024 3:01 PM        CTN
1557            0    Hina Shah Jun 26, 2024 3:01 PM        CTN
1558            0    Hina Shah May 23, 2025 2:38 PM        CTN
1559            0    Hina Shah May 23, 2025 2:38 PM        CTN
1560            0    Hina Shah May 23, 2025 2:38 PM        CTN
1561            0    Hina Shah May 23, 2025 2:38 PM        CTN
1562            0   Hina Shah Feb 20, 2026 12:40 AM        CTN
1563         61.5   Hina Shah Feb 20, 2026 12:40 AM        CTN
1568          NaN  Kathy Jooss May 4, 2023 12:25 PM        NaN
1569          NaN  Kathy Jooss May 4, 2023 12:25 PM        NaN
1570          NaN  Kathy Jooss Nov 29, 2021 9:34 AM        NaN
1571          NaN  Kathy Jooss Nov 29, 2021 8:59 AM        NaN

                        "Get the Data" Engagement Board       VLMD Status  \
1518             CTN - Margaret Wadle (c/o Randy Boley)               NaN
1519              CTN - Kimberly Page/Janet Page-Reeves  VLMD on Platform
1520                             CTN - Stephanie Hooker  VLMD on Platform
1521                               CTN - Gerald Cochran  VLMD on Platform
1522                                                NaN               NaN
1523                            CTN0099- Gail D'Onofrio               NaN
1524                         CTN - Richard Schottenfeld               NaN
1525                              CTN - Jose Szapocznik               NaN
1526                  CTN - Gail D'Onfrio (Patti Owens)               NaN
1527                               CTN - Rebecca Rossum               NaN
1528                                                NaN               NaN
1529                             CTN0145 Gail D'Onofrio               NaN
1530                                                NaN               NaN
1531                                                NaN               NaN
1532                      Cynthia Campbell - CTN 0084A1     VLMD unlikely
1533                                CTN - Brenda Stuvek               NaN
1534                                CTN - Rebecca Stone     VLMD received
1535                              CTN - Jane Liebschutz               NaN
1536                                    CTN - Li-Tzy Wu     VLMD received
1537                                                NaN               NaN
1538                               CTN - Ryan McCormack               NaN
1539                                  CTN - Susan Sonne               NaN
1540                                                NaN               NaN
1541                     CTN - Ned Nunes (c/o Sean Luo)               NaN
1542                                  CTN - Lisa Marsch               NaN
1543                 CTN - Adam Gordon c/o Jacob Baylis  VLMD on Platform
1544                                                NaN               NaN
1545                      CTN - Rebecca Rossum (0095A1)  VLMD on Platform
1546                                                NaN               NaN
1547                                 CTN - Yih-Ing Hser               NaN
1548                                                NaN               NaN
1549                             CTN - T. John Winhusen               NaN
1550                        CTN 0084 - Cynthia Campbell     VLMD received
1551                           CTN 0074A1 - Sean Murphy               NaN
1552             CTN - Adam Bisaga c/o Jennifer McNeely     VLMD received
1553  CTN - Madhukar Trivedi (c/o Angela Casey-Willi...               NaN
1554                      Kamilla Venner/Aimee Campbell               NaN
1555                                                NaN               NaN
1556                                  CTN - Sean X. Luo               NaN
1557                                                NaN               NaN
1558                                                NaN               NaN
1559                                                NaN               NaN
1560                                                NaN               NaN
1561                                                NaN               NaN
1562                                                NaN               NaN
1563                                                NaN               NaN
1568                                                NaN               NaN
1569                                                NaN               NaN
1570                                                NaN               NaN
1571                                                NaN               NaN

                      DD Tracker Checklist Exempt Do not Engage  \
1518                         NaN                N             N
1519                    HDP01286                N             N
1520                    HDP01287                N             N
1521  CTN0093-DataDictionary.xlx                N             N
1522                         NaN                N             N
1523                         NaN                N             N
1524                         NaN                N             N
1525                         NaN                N             N
1526                         NaN                N             N
1527                         NaN                N             N
1528                         NaN                N             N
1529                         NaN                N             N
1530                         NaN                N             N
1531                         NaN                N             N
1532                         NaN                N             N
1533                         NaN                N             N
1534                    HDP01301                N             N
1535                         NaN                N             N
1536                    HDP01303                N             N
1537                         NaN                N             N
1538                         NaN                N             N
1539                         NaN                N             N
1540                         NaN                N             N
1541                         NaN                N             N

In [9]:
# import pandas as pd
# def get_unique_values(df:pd.DataFrame, col_name:str='appl_id'):
#     if col_name in df.columns:
#         return df[ ~pd.isna(df[col_name])][col_name].drop_duplicates()
#     return None

# convert_dict = {'appl_id':str}
# resnet_df = pd.read_csv(input_dir/"research_networks.csv", low_memory=False, dtype=convert_dict)
# logging.info(f"Research Network table has: {len(resnet_df)} entrie, with {len(get_unique_values(resnet_df))} appl_ids")
# print(resnet_df.columns)
# appl_ids = gt_file[['appl_id', 'study_most_recent_appl']].drop_duplicates()
# print(len(appl_ids))
# resnet_added = pd.merge(appl_ids, resnet_df[['appl_id', 'res_net']], how = 'left', left_on='appl_id', right_on='appl_id' )
# print(len(resnet_added))
# resnet_most_recent_appl_id = resnet_added[~pd.isna(resnet_added.res_net)][['study_most_recent_appl', 'res_net']]
# resnet_added_updated = pd.merge(appl_ids, resnet_most_recent_appl_id, how='left', left_on='study_most_recent_appl', right_on='study_most_recent_appl')
# resnet_added_updated.to_csv("/tmp/tmp_resnet_updated.csv", index=False)

In [10]:
logging.info("---- STEP 4: Importing tables from MySQL and combining relevant information")
combined_data_ph1 = monday_board_update.import_mysql_data(input_dir, gt_file, monday_board, lookup_fields)

---- STEP 4: Importing tables from MySQL and combining relevant information
Awards table has: 2443 entries, with 2442 appl_ids
*** Combining the two reporter tables
2442
489
2931
Reporter table has: 2931 entries, with 2931 appl_ids
Platform generated table has: 1714 entries, with 1615 appl_ids
Platform table has 1615 unique HDP IDs
Repo mapping table has: 1748 entries, with 1748 appl_ids
Research Network table has: 2443 entries, with 2443 appl_ids
Engagment Flags table has: 2627 entries, with 2627 appl_ids
PO Emails table has: 2442 entries, with 2442 appl_ids
--- Wrangling PI Emails
ALL PI emails associated with a project (identified by most_recent_appl)
      study_most_recent_appl               pi_email_latest
1                   9755001             kwatkins@rand.org
3                  10088639               damico@rand.org
4                  11195709         acfernan@med.umich.ed
6                  11196080               fqeadan@luc.edu
8                   9869480             LYNN.DEBAR@KP.ORG
...                     ...                           ...
2617               11193636         monica.kraft@mssm.edu
2618               11195200  lucila.ohno-machado@yale.edu
2619               11193592        szuchner@med.miami.edu
2625               11179276       danny.benjamin@duke.edu
2627               11167601       william.becker@yale.edu

[1391 rows x 2 columns]
Statistics on number of emails per project::
 count    1304.000000
mean        1.066718
std         0.255703
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         3.000000
dtype: float64
Emails that were kept for each project when there's only one email available, or when email is available for the most recent award (study_most_recent_appl)
     study_most_recent_appl                      pi_email
0                   9860408
1                   9755001             kwatkins@rand.org
3                  10088639               damico@rand.org
4                  11195709         acfernan@med.umich.ed
6                  11196080               fqeadan@luc.edu
...                     ...                           ...
2618               11195200  lucila.ohno-machado@yale.edu
2619               11193592        szuchner@med.miami.edu
2620               10021038
2625               11179276       danny.benjamin@duke.edu
2627               11167601       william.becker@yale.edu

[1596 rows x 2 columns]
Adding any Monday Board emails when emails missing from MySql. Data looks like:
     study_most_recent_appl                      pi_email  \
0                   9860408
1                   9755001             kwatkins@rand.org
2                  10088639               damico@rand.org
3                  11195709         acfernan@med.umich.ed
4                  11196080               fqeadan@luc.edu
...                     ...                           ...
1591               11195200  lucila.ohno-machado@yale.edu
1592               11193592        szuchner@med.miami.edu
1593               10021038
1594               11179276       danny.benjamin@duke.edu
1595               11167601       william.becker@yale.edu

                     Contact Email              pi_email_updated
0
1                kwatkins@rand.org             kwatkins@rand.org
2                  damico@rand.org               damico@rand.org
3            acfernan@med.umich.ed         acfernan@med.umich.ed
4                  fqeadan@luc.edu               fqeadan@luc.edu
...                            ...                           ...
1591  lucila.ohno-machado@yale.edu  lucila.ohno-machado@yale.edu
1592        szuchner@med.miami.edu        szuchner@med.miami.edu
1593
1594       danny.benjamin@duke.edu       danny.benjamin@duke.edu
1595       william.becker@yale.edu       william.becker@yale.edu

[1596 rows x 4 columns]
---- STEP 5: Gathering relevant data fields from MySQL tables
Number of fields from lookup table: 1631
Number of fields after adding reporter table fields: 1631
Number of fields after adding awards table fields: 1631
Number of fields after adding Platform MDS table fields: 1631
Number of fields after adding research network table fields: 1631
Number of fields after adding engagegment flag table fields: 1631
Number of fields after adding PO Emai fields: 1631
Number of fields after adding PI Emails: 1631
Total entries in this combined dataset: 1631

In [11]:
logging.info("---- STEP 5: Filling holes with MDS data")
combined_data_ph1 = monday_board_update.fill_in_holes_from_mds(input_dir, combined_data_ph1)

---- STEP 5: Filling holes with MDS data

In [12]:
    ## Add CTN  data
logging.info("---- STEP 6: Adding any CTN data from MDS")
ctn_fields_platform = monday_board_update.get_ctndata_from_mds(input_dir)

---- STEP 6: Adding any CTN data from MDS
Number of CTN entries found in Platform MDS 46

/Users/hinashah/code/HEAL/metadata-sync/notebooks/../scripts/monday_board_update.py:334: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ctn_data['project_title'] = ctn_data['project_title'].replace('0', '')

In [13]:
logging.info("---- STEP 7: Combining everything together")
all_data = monday_board_update.combine_mysql_ctn(combined_data_ph1, ctn_fields_platform)

---- STEP 7: Combining everything together
------------ Preview of the final combined dataset ---------------
     Activity Code Administering IC Archived Award Type  Award Year  \
0              U01            NIAAA     live          3      2019.0
1              R34            NIAAA     live          3      2019.0
2              R01            NIAAA     live          3      2020.0
3              R34            NIAAA     live          5      2025.0
4              R01            NIAAA     live          5      2025.0
...            ...              ...      ...        ...         ...
1499           NaN              NaN     live          0         NaN
1500           NaN              NaN     live          0         NaN
1501           NaN              NaN     live          0         NaN
1680           NaN              NaN     live          0         NaN
1681           NaN              NaN     live          0         NaN

      CEDAR Form %  Checklist Exempt          City          Contact Email  \
0              0.0               0.0      PORTLAND
1              0.0               0.0  SANTA MONICA      kwatkins@rand.org
2              0.0               0.0  SANTA MONICA        damico@rand.org
3             80.8               1.0     ANN ARBOR  acfernan@med.umich.ed
4              0.0               1.0       MAYWOOD        fqeadan@luc.edu
...            ...               ...           ...                    ...
1499           0.0               NaN           NaN                    NaN
1500           0.0               NaN           NaN                    NaN
1501           0.0               NaN           NaN                    NaN
1680           0.0               NaN           NaN                    NaN
1681          61.5               NaN           NaN                    NaN

                    Contact PI  ...  \
0              NAGEL, BONNIE J  ...
1         WATKINS, KATHERINE E  ...
2        D'AMICO, ELIZABETH J.  ...
3     FERNANDEZ, ANNE CHRISTIE  ...
4                QEADAN, FARES  ...
...                        ...  ...
1499                       NaN  ...
1500                       NaN  ...
1501                       NaN  ...
1680                       NaN  ...
1681                       NaN  ...

                                                Summary  \
0     PROJECT SUMMARY. During young adulthood, drink...
1     PROJECT SUMMARY/ABSTRACT. Substance use disord...
2     Summary/Abstract. This administrative suppleme...
3     Opioid agonist therapies (i.e. buprenorphine a...
4     Project Summary/Abstract. The intersection of ...
...                                                 ...
1499  Low-threshold Buprenorphine Treatment at Syrin...
1500  Evaluation of Tirzepatide as an Adjunct to Bup...
1501  EMS initiated Buprenorphine for Opioid Use Dis...
1680  Extended-Release vs Sublingual Buprenorphine f...
1681  EXHIT ENTRE Implementation Trial of High Inten...

                                                  Title  Total Funded  \
0     National Consortium on Alcohol and Neurodevelo...       93429.0
1     Implementing Medication-Assisted Therapy for S...       99988.0
2     AOD Use Trajectories from Age 10 to 24: Multi-...       99999.0
3     Cultivating Recovery: A Pilot Study of Digital...      390000.0
4     Advancing Integrated Treatment for Co-Occurrin...      385000.0
...                                                 ...           ...
1499                                                NaN           0.0
1500                                                NaN           0.0
1501                                                NaN           0.0
1680                                                NaN           0.0
1681                                                NaN           0.0

      hdp_id_x  hdp_id_y       key study_hdp_id study_hdp_id_appl  \
0     HDP00632  HDP00632  HDP00632     HDP00632           9860408
1     HDP00696  HDP00696  HDP00696     HDP00696           9755001
2     HDP00509  HDP00509  HDP00509     HDP00509           9850412
3     HDP01356  HDP01356  HDP01356     HDP01356          10996795
4     HDP01380  HDP01380  HDP01380     HDP01380          11001407
...        ...       ...       ...          ...               ...
1499       NaN       NaN  HDP01505     HDP01505               NaN
1500       NaN       NaN  HDP01506     HDP01506               NaN
1501       NaN       NaN  HDP01507     HDP01507               NaN
1680       NaN       NaN  HDP01686     HDP01686               NaN
1681       NaN       NaN  HDP01687     HDP01687               NaN

     study_most_recent_appl    hdp_id
0                   9860408       NaN
1                   9755001       NaN
2                  10088639       NaN
3                  11195709       NaN
4                  11196080       NaN
...                     ...       ...
1499                    NaN  HDP01505
1500                    NaN  HDP01506
1501                    NaN  HDP01507
1680                    NaN  HDP01686
1681                    NaN  HDP01687

[1677 rows x 38 columns]
==== Frequencies of several research networks in the combined dataset ========
Research Network
                       1027
HBCD                    124
JCOIN                    84
BACPAC                   59
CTN                      46
NCREW                    36
ACT NOW                  35
EPPIC-NET                33
PAIN ERN                 31
DATA 2 ACTION            31
PRISM                    28
HPC                      27
IMPOWR                   21
HOPE                     15
RISE                     14
HEALING COMMUNITIES      12
PRECISION                11
IGNITE                    8
MEDTECH                   8
HEAL KIDS                 8
RE-JOIN                   7
MIRHIQL                   5
A2CPS                     5
MFMU                      2
Name: count, dtype: int64
Fields and frequencies of any empty values in the final dataset
{'Activity Code': 48,
 'Administering IC': 48,
 'Archived': 117,
 'Award Year': 46,
 'CEDAR Form %': 117,
 'Checklist Exempt': 46,
 'City': 53,
 'Contact Email': 46,
 'Contact PI': 48,
 'Data Type': 1288,
 'Do not Engage': 46,
 'HEAL-Related': 238,
 'Institution(s)': 48,
 'NIH PO': 122,
 'NIH PO Email': 307,
 'Platform Reg Time': 1101,
 'Project End': 46,
 'Project Start': 60,
 'Repo per Platform': 1234,
 'Reporter Link': 46,
 'Research Focus': 254,
 'Research Program': 380,
 'SBIR/STTR': 48,
 'State': 55,
 'Title': 46,
 'hdp_id': 1631,
 'hdp_id_x': 163,
 'hdp_id_y': 163,
 'study_hdp_id': 117,
 'study_hdp_id_appl': 163,
 'study_most_recent_appl': 46}

In [14]:
all_data[all_data.key=='HDP00108'][['Project Start', 'Project End']]

            Project Start          Project End
1470  2021-02-18T00:00:00  2026-01-31T00:00:00

In [15]:
logging.info("---- STEP 8: Final Manipulation of all the data to make it Monday Board ready")
combined_data = monday_board_update.prepare_for_monday(all_data)

---- STEP 8: Final Manipulation of all the data to make it Monday Board ready
Counts for study types in the final dataset
study_type
HDP           1514
APPLIDONLY     117
CTN             46
Name: count, dtype: int64
Setting empty cells to  '-' in the following colulmns:
['Activity Code', 'Administering IC', 'Award Type', 'Contact Email', 'Contact PI', 'Data Type', 'Institution(s)', 'NIH PO', 'NIH PO Email', 'PI(s)', 'Project #', 'Repo per Platform', 'Reporter Link', 'Research Focus', 'Research Network', 'Research Program', 'Summary', 'Title', 'key', 'HDP appl_ID', 'Most Recent Appl_ID']

In [16]:
combined_data[combined_data.key=='HDP00108'][['Project Start', 'Project End']]

     Project Start Project End
1470    2021-02-18  2026-01-31

In [17]:
logging.info("---- STEP 9: Final numbers and Export")
monday_board_update.export_finaldata(input_dir, combined_data, mondayboard_missingin_lookup, monday_board)

---- STEP 9: Final numbers and Export
******************* MONDAY COMPARISON  ******************************************
Number records from Monday already in final dataset: 1677
Number records from Monday that are not in final dataset (Consider these as discrepancies **Investigate**): 4
Number records from final dataset that are not on Monday (Potentially new entries): 0
****** Investigate/Delete the following entries on Monday that are not in the final dataset
[['10428343_HDP00882' nan nan]
 ['10488140_HDP00883' nan nan]
 ['9673173_none' nan nan]
 ['9769689_none' nan nan]]
******************* FINAL DATASET NUMBERS ******************************************
Number records in the final dataset: 1677
Making sure uniqueness of key values. Do we have one row per key(HDPID/APPLID)? ::::  True
******************* EXPORTING ******************************************
Exporting data to excel file at /Users/hinashah/Documents/HEAL/MondayUpdate_May2026/MondayBoard_Update.xlsx
Exporting batch 1 (1000 records) to /Users/hinashah/Documents/HEAL/MondayUpdate_May2026/MondayBoard_Update_batch_1_records_1_to_1000.xlsx
Exporting batch 2 (677 records) to /Users/hinashah/Documents/HEAL/MondayUpdate_May2026/MondayBoard_Update_batch_2_records_1001_to_1677.xlsx
******************* DONE! ******************************************

In [18]:
mondayboard_missingin_lookup[~(mondayboard_missingin_lookup.study_type == 'CTN')].Name.values

array(['10428343_HDP00882', '10488140_HDP00883', '9673173_none',
       '9769689_none'], dtype=object)

In [19]:
"""
If the answer to: Making sure uniqueness of key values. Do we have one row per key(HDPID/APPLID)? is False, 
Run the script here.
"""
counts = combined_data.key.value_counts()
counts[counts > 1]

Series([], Name: count, dtype: int64)

In [20]:
combined_data[combined_data.key == 'HDP01187']

,Activity Code,Administering IC,Archived,Award Type,Award Year,CEDAR Form %,Checklist Exempt,City,Contact Email,Contact PI,...,SBIR/STTR,State,Summary,Title,Total Funded,key,HDP appl_ID,Most Recent Appl_ID,study_type,Location
index,,,,,,,,,,,,,,,,,,,,,
760,R33,NIDA,n,5,2025.0,7.7,N,NEW YORK,Charles.Neighbors@nyulangone.org,"NEIGHBORS, CHARLES J",...,N,NY,Regulatory changes made in 2020 that relaxed c...,Leveraging regulatory flexibility for methadon...,1089537.0,HDP01187,10878304,11189778,HDP,"NEW YORK,NY"

In [21]:
import pandas as pd

def get_unique_values(df:pd.DataFrame, col_name:str='appl_id'):
    if col_name in df.columns:
        return df[ ~pd.isna(df[col_name])][col_name].drop_duplicates()
    return None

convert_dict = {'appl_id':str}
resnet_df = pd.read_csv(input_dir/"research_networks.csv", low_memory=False, dtype=convert_dict)
logging.info(f"Research Network table has: {len(resnet_df)} entries, with {len(get_unique_values(resnet_df))} appl_ids")

appl_ids = gt_file[['appl_id', 'study_most_recent_appl']].drop_duplicates()
resnets = resnet_df[~pd.isna(resnet_df.res_net)][['appl_id', 'res_net']]

resnets_merged = pd.merge(appl_ids, resnets, how='left', left_on='study_most_recent_appl', right_on='appl_id')
resnets_merged_again = pd.merge(resnets_merged, resnets, how='left', left_on='appl_id_x', right_on='appl_id')

resnets_merged_again.drop_duplicates(inplace=True)
resnets_merged_again.to_csv("/tmp/resnet.csv")

Research Network table has: 2443 entries, with 2443 appl_ids

In [22]:
resnet_added = pd.merge(appl_ids, resnet_df[['appl_id', 'res_net']], how = 'left', left_on='appl_id', right_on='appl_id' )
resnet_most_recent_appl_id = resnet_added[~pd.isna(resnet_added.res_net)][['study_most_recent_appl', 'res_net']]
resnet_added_updated = pd.merge(appl_ids, resnet_most_recent_appl_id, how='left', left_on='study_most_recent_appl', right_on='study_most_recent_appl')
resnet_df_new = resnet_added_updated[['study_most_recent_appl', 'res_net']].drop_duplicates()
resnet_added_updated.to_csv("/tmp/tmp_resnet_udpated.csv", index=False)

In [23]:
### BLOCK to compare Platform MDS list of studies vs. Monday Board studies.


import requests
mds_metadata_endpoint = 'https://healdata.org/mds/metadata'
HEAL_STUDY_GUID_TYPES = [
    'discovery_metadata',                   # Fully registered studies.
    'unregistered_discovery_metadata'       # Studies added to the Platform MDS but without the investigator registering the study.
]

metadata_ids = []
for heal_study_guid_type in HEAL_STUDY_GUID_TYPES:
    result = requests.get(mds_metadata_endpoint, params={
            '_guid_type': heal_study_guid_type,
            'limit': 2000,
        })
    if not result.ok:
            print(f'Could not retrieve metadata list for guid_type {heal_study_guid_type}: {result}')
    metadata_ids.extend(result.json())

print(len(metadata_ids))

Starting new HTTPS connection (1): healdata.org:443
https://healdata.org:443 "GET /mds/metadata?_guid_type=discovery_metadata&limit=2000 HTTP/11" 200 None
Starting new HTTPS connection (1): healdata.org:443
https://healdata.org:443 "GET /mds/metadata?_guid_type=unregistered_discovery_metadata&limit=2000 HTTP/11" 200 None
1153

In [24]:
hdps_platform = combined_data[(combined_data.study_type.isin(['HDP', 'CTN'])) & (combined_data['Archived'] != 'archived')]
print(len(hdps_platform))

1123

In [25]:
missing_hdps = [k for k in metadata_ids if k not in hdps_platform.key.values]
missing_hdps.sort()
print(len(missing_hdps))
for k in missing_hdps:
    print(k)

30
HDP01513
HDP01514
HDP01515
HDP01516
HDP01517
HDP01518
HDP01519
HDP01697
HDP01698
HDP01699
HDP01700
HDP01701
HDP01702
HDP01703
HDP01704
HDP01705
HDP01706
HDP01707
HDP01708
HDP01709
HDP01710
HDP01711
HDP01712
HDP01713
HDP01714
HDP01715
HDP01716
HDP01717
HDP01718
HDP01722